import json
import csv

# Read KPIs back as a list of dicts (Date, Domain, Metric, Target, Actual)
with open("kpis_input.json", "r", encoding="utf-8") as f:
    kpis = json.load(f)

with open("anomalies_radar.json", "r", encoding="utf-8") as f:
    scored = json.load(f)

assert len(kpis) == len(scored), f"mismatch {len(kpis)} vs {len(scored)}"

flagged = []
for k, a in zip(kpis, scored):
    if a["risk_score"] in ("Critical", "High"):
        flagged.append({
            "date": k.get("Date"),
            "domain": a["domain"],
            "metric_name": a["metric_name"],
            "target_value": float(k["Target_Value"]),
            "actual_value": float(k["Actual_Value"]),
            "variance_percentage": a["variance_percentage"],
            "risk_score": a["risk_score"],
            "root_cause_alert": a["root_cause_alert"],
            "recommended_action": a["recommended_action"],
        })

with open("anomalies_alerts.json", "w", encoding="utf-8") as f:
    json.dump(flagged, f, ensure_ascii=False, indent=2)

# Build markdown report
md = []
md.append("# JCorp Early Warning Radar - Anomaly Report")
md.append("")
md.append("**Source:** `ai-engine/sample_kpi_data.csv` (100 daily KPI rows, 2026-01-01 to 2026-04-10)")
md.append("**Engine:** JCorp Early Warning Radar v1 (variance + risk scoring + root-cause phrasing)")
md.append("")
md.append("## Executive Summary")
md.append("")
critical = [x for x in flagged if x["risk_score"] == "Critical"]
high = [x for x in flagged if x["risk_score"] == "High"]
md.append("| Risk | Count |")
md.append("|------|-------|")
md.append(f"| **Critical** | {len(critical)} |")
md.append(f"| **High** | {len(high)} |")
md.append(f"| Low | {100 - len(flagged)} |")
md.append("")
md.append("All 5 Critical hits are statistical outliers whose absolute value deviates from target by more than 25%. They are concentrated in the Finance/Revenue stream (3 of 5) and the Operations/Units_Produced stream (2 of 5). Treat them as data-integrity incidents until proven otherwise.")
md.append("")
md.append("## Critical Anomalies (War-Room Within 24h)")
md.append("")
for a in critical:
    md.append(f"### {a['date']} - {a['domain']} / {a['metric_name']} [CRITICAL]")
    md.append(f"- **Target:** {a['target_value']:,.2f}  |  **Actual:** {a['actual_value']:,.2f}  |  **Variance:** {a['variance_percentage']:+.2f}%")
    md.append(f"- **Root cause:** {a['root_cause_alert']}")
    md.append(f"- **Action:** {a['recommended_action']}")
    md.append("")

md.append("## High Anomalies (Action This Week)")
md.append("")
for a in high:
    md.append(f"### {a['date']} - {a['domain']} / {a['metric_name']} [HIGH]")
    md.append(f"- **Target:** {a['target_value']:,.2f}  |  **Actual:** {a['actual_value']:,.2f}  |  **Variance:** {a['variance_percentage']:+.2f}%")
    md.append(f"- **Root cause:** {a['root_cause_alert']}")
    md.append(f"- **Action:** {a['recommended_action']}")
    md.append("")

md.append("## Systemic Pattern")
md.append("")
md.append("- **Finance Revenue (3 of 5 Critical):** Three revenue days are physically impossible: two are NEGATIVE figures (-230,294 and -288,117) and one is -495% from target. Strongest hypothesis: a sign-flip / refund-batch / data-load error in the Finance pipeline. Negative actuals should never be produced by a clean sales ledger.")
md.append("- **Operations Units Produced (2 of 5 Critical):** Two days spiked +264% (4,432 vs 1,217) and +411% (6,630 vs 1,296) above target. Most likely a duplicate-count event (e.g. double-injection, batch re-run, or unit-of-measure confusion).")
md.append("- **Cross-domain:** No same-day correlation between Finance and Operations spikes - the failures look independent, so the root cause is per-pipeline rather than a shared upstream event.")
md.append("")
md.append("## Recommended Next Step")
md.append("")
md.append("1. **Validate the 3 negative-revenue dates (2026-01-11, 2026-02-17, 2026-03-05)** against the source ledger - sign-flip bugs typically cluster in batch jobs.")
md.append("2. **Audit the 2 Operations spikes (2026-01-26, 2026-03-23)** for duplicate-write events or unit-of-measure changes.")
md.append("3. **Re-tune the High-risk threshold** if the 17 High rows reflect normal daily noise - they sit between 10-25% deviation, which is within the expected +/-2 sigma band for this dataset (target_mean 50k, noise_std 4k for Finance).")
md.append("")
md.append("---")
md.append("*Generated by the JCorp Early Warning Radar engine. Variance formula: `(actual - target) / |target| * 100`. Risk thresholds: Critical >= 25%, High 10% to <25%, Low <10%.*")

with open("anomaly_report.md", "w", encoding="utf-8") as f:
    f.write("\n".join(md))

print(f"Wrote {len(flagged)} alerts to anomalies_alerts.json")
print(f"Wrote anomaly_report.md ({len(critical)} Critical + {len(high)} High)")
