<?php

namespace App\Http\Controllers;

class DashboardController extends Controller
{
    public function index()
    {
        // Read the JSON file generated by the AI engine
        $jsonPath = base_path('../ai-engine/anomalies_alerts.json');
        $alerts   = [];

        if (file_exists($jsonPath)) {
            $json   = file_get_contents($jsonPath);
            $alerts = json_decode($json, true) ?? [];
        }

        // Sort: Critical first, then High, then everything else
        usort($alerts, function ($a, $b) {
            $rank = ['Critical' => 0, 'High' => 1];
            $ra   = $rank[$a['risk_score']] ?? 2;
            $rb   = $rank[$b['risk_score']] ?? 2;
            return $ra <=> $rb;
        });

        // Summary counts
        $criticalCount = count(array_filter($alerts, fn($a) => $a['risk_score'] === 'Critical'));
        $highCount     = count(array_filter($alerts, fn($a) => $a['risk_score'] === 'High'));
        $lowCount      = count(array_filter($alerts, fn($a) => !in_array($a['risk_score'], ['Critical', 'High'])));
        $totalCount    = count($alerts);

        return view('dashboard', compact('alerts', 'criticalCount', 'highCount', 'lowCount', 'totalCount'));
    }
}
